version: '3.2'
services:
  db:
    container_name: my_db
    image: postgres
    restart: on-failure
    ports:
      - '5440:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
